title: Jordan Daniel
logo:
description: A portfolio of my work
remote_theme: abhinavs/moonwalk
appearance: "dark" # can be "light", "dark" or "auto"
appearance_toggle: true # if appearance can be switched by user
